package jpanelemail;

import java.awt.Color;
import java.awt.Font;
import java.io.Serializable;
import org.apache.commons.validator.routines.EmailValidator;

/**
 *
 * @author David
 */
public class JPanelEmail extends javax.swing.JPanel implements Serializable {

    private String nombreJlabelEmail;
    private String hint;
    private String emailNoValido;

    private Color nombreJlabelEmailColor;
    private Color hintColor;
    private Color emailNoValidoColor;

    private Font nombreJlabelEmailFont;
    private Font hintFont;
    private Font emailNoValidoFont;

    public JPanelEmail() {
        initComponents();
        this.jLabelValidate.setVisible(false);

        this.nombreJlabelEmail = "Correo electrónico:";
        this.hint = "usuario@dominio.com";
        this.emailNoValido = "El email no es válido";

        this.nombreJlabelEmailColor = this.jLabelNombre.getForeground();
        this.hintColor = this.jLabelHint.getForeground();
        this.emailNoValidoColor = this.jLabelValidate.getForeground();

        this.nombreJlabelEmailFont = this.jLabelNombre.getFont();
        this.hintFont = this.jLabelHint.getFont();
        this.emailNoValidoFont = this.jLabelValidate.getFont();
    }

    public String getNombreJlabelEmail() {
        return nombreJlabelEmail;
    }

    public void setNombreJlabelEmail(String nombreJlabelEmail) {
        this.nombreJlabelEmail = nombreJlabelEmail;
        this.jLabelNombre.setText(this.nombreJlabelEmail);
    }

    public String getHint() {
        return hint;
    }

    public void setHint(String hint) {
        this.hint = hint;
        this.jLabelHint.setText(this.hint);
    }

    public String getEmailNoValido() {
        return emailNoValido;
    }

    public void setEmailNoValido(String emailNoValido) {
        this.emailNoValido = emailNoValido;
        this.jLabelValidate.setText(this.emailNoValido);
    }

    public Color getNombreJlabelEmailColor() {
        return nombreJlabelEmailColor;
    }

    public Color getHintColor() {
        return hintColor;
    }

    public Color getEmailNoValidoColor() {
        return emailNoValidoColor;
    }

    public void setNombreJlabelEmailColor(Color nombreJlabelEmailColor) {
        this.nombreJlabelEmailColor = nombreJlabelEmailColor;
        this.jLabelNombre.setForeground(this.nombreJlabelEmailColor);
    }

    public void setHintColor(Color hintColor) {
        this.hintColor = hintColor;
        this.jLabelHint.setForeground(this.hintColor);
    }

    public void setEmailNoValidoColor(Color emailNoValidoColor) {
        this.emailNoValidoColor = emailNoValidoColor;
        this.jLabelValidate.setForeground(this.emailNoValidoColor);
    }

    public Font getNombreJlabelEmailFont() {
        return nombreJlabelEmailFont;
    }

    public Font getHintFont() {
        return hintFont;
    }

    public Font getEmailNoValidoFont() {
        return emailNoValidoFont;
    }

    public void setNombreJlabelEmailFont(Font nombreJlabelEmailFont) {
        this.nombreJlabelEmailFont = nombreJlabelEmailFont;
        this.jLabelNombre.setFont(this.nombreJlabelEmailFont);
    }

    public void setHintFont(Font hintFont) {
        this.hintFont = hintFont;
        this.jLabelHint.setFont(this.hintFont);
    }

    public void setEmailNoValidoFont(Font emailNoValidoFont) {
        this.emailNoValidoFont = emailNoValidoFont;
        this.jLabelValidate.setFont(this.emailNoValidoFont);
    }

    private boolean validateEmail(String email) {
        EmailValidator validator = EmailValidator.getInstance();
        return validator.isValid(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHint = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelValidate = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();

        setLayout(null);

        jLabelHint.setForeground(new java.awt.Color(204, 204, 204));
        jLabelHint.setText("usuario@dominio.com");
        add(jLabelHint);
        jLabelHint.setBounds(30, 110, 120, 20);

        jLabel1.setText("Nombre:");
        add(jLabel1);
        jLabel1.setBounds(21, 6, 60, 16);

        jLabelNombre.setText("Correo electrónico:");
        add(jLabelNombre);
        jLabelNombre.setBounds(20, 76, 240, 30);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        add(jTextField1);
        jTextField1.setBounds(21, 28, 240, 29);

        jLabelValidate.setForeground(new java.awt.Color(255, 51, 51));
        jLabelValidate.setText("El email no es válido");
        add(jLabelValidate);
        jLabelValidate.setBounds(20, 160, 240, 26);

        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });
        add(jTextFieldEmail);
        jTextFieldEmail.setBounds(20, 110, 240, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        if (validateEmail(this.jTextFieldEmail.getText())) {
            this.jLabelValidate.setVisible(false);
            this.jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        } else {
            this.jLabelValidate.setVisible(true);
            this.jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        this.jLabelHint.setText("");
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (this.jTextFieldEmail.getText().equals("")) {
            this.jLabelHint.setText(this.hint);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelValidate;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables

}
