
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class FormularioPrestamo extends javax.swing.JDialog {

    /**
     * Creates new form FormularioPrestamo
     */
    public FormularioPrestamo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        topics(jComboBoxMaterias.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIsbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEditorial = new javax.swing.JComboBox<>();
        jComboBoxTipoEncu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxMaterias = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jSpinnerFechaPrestamo = new javax.swing.JSpinner();
        jSpinnerFechaEntrega = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBoxOpcion1 = new javax.swing.JCheckBox();
        jCheckBoxOpcion2 = new javax.swing.JCheckBox();
        jCheckBoxOpcion3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulario de recogida de datos");
        setBackground(new java.awt.Color(0, 153, 153));

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nombre y Apellidos:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("DNI:");

        jTextFieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDniKeyTyped(evt);
            }
        });

        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Teléfono:");

        jTextFieldIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIsbnKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("ISBN:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Título del libro:");

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jTextFieldAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAutorKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Autor del libro:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Editorial:");

        jComboBoxEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urano Ediciones", "Círculo rojo", "Vicens Vives", "Altamar" }));
        jComboBoxEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditorialActionPerformed(evt);
            }
        });

        jComboBoxTipoEncu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rústica", "Tapa dura", "Piel" }));
        jComboBoxTipoEncu.setVisible(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de encuadernación:");
        jLabel8.setVisible(false);

        jComboBoxMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentación-Nutrición", "Medicina", "Derecho", "Música" }));
        jComboBoxMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMateriasActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Materias:");

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar registro");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jSpinnerFechaPrestamo.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jSpinnerFechaEntrega.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Fecha préstamo libro:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Fecha entrega libro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpinnerFechaPrestamo)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerFechaEntrega)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMaterias, 0, 191, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEditorial, 0, 191, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipoEncu, 0, 191, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxOpcion3)
                                    .addComponent(jCheckBoxOpcion1)
                                    .addComponent(jCheckBoxOpcion2)))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoEncu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxOpcion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxOpcion2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxOpcion3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        String nombreApellidos = jTextFieldNombre.getText();
        String titulo = jTextFieldTitulo.getText();
        String dni = jTextFieldDni.getText();
        String autor = jTextFieldAutor.getText();
        String telefono = jTextFieldTelefono.getText();
        String isbn = jTextFieldIsbn.getText();

        if (!(nombreApellidos.equals("") && titulo.equals("") && dni.equals("") && autor.equals("") && telefono.equals("") && isbn.equals(""))) {
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Realmente quieres salir?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                dispose();
            }
            
        } else {
            dispose();
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void jComboBoxEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditorialActionPerformed
        int indice = jComboBoxEditorial.getSelectedIndex();

        if (indice == 1 || indice == 2) {
            jComboBoxTipoEncu.setVisible(true);
            jLabel8.setVisible(true);
        } else {
            jComboBoxTipoEncu.setVisible(false);
            jLabel8.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxEditorialActionPerformed

    private void jComboBoxMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMateriasActionPerformed
        jCheckBoxOpcion1.setSelected(false);
        jCheckBoxOpcion2.setSelected(false);
        jCheckBoxOpcion3.setSelected(false);
        topics(jComboBoxMaterias.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxMateriasActionPerformed

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        int limiteCaracteres = 30;
        if (jTextFieldNombre.getText().length() >= limiteCaracteres) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniKeyTyped
        int limiteCaracteres = 10;
        if (jTextFieldDni.getText().length() >= limiteCaracteres) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDniKeyTyped

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
        int limiteCaracteres = 9;
        char caracter = evt.getKeyChar();

        if (jTextFieldTelefono.getText().length() >= limiteCaracteres) {
            evt.consume();
        }

        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jTextFieldIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIsbnKeyTyped
        int limiteCaracteres = 13;
        char caracter = evt.getKeyChar();

        if (jTextFieldIsbn.getText().length() >= limiteCaracteres) {
            evt.consume();
        }

        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIsbnKeyTyped

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        int limiteCaracteres = 30;
        if (jTextFieldTitulo.getText().length() >= limiteCaracteres) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAutorKeyTyped
        int limiteCaracteres = 20;
        if (jTextFieldAutor.getText().length() >= limiteCaracteres) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAutorKeyTyped

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        String nombreApellidos = jTextFieldNombre.getText();
        String titulo = jTextFieldTitulo.getText();
        String dni = jTextFieldDni.getText();
        String autor = jTextFieldAutor.getText();
        String telefono = jTextFieldTelefono.getText();
        String isbn = jTextFieldIsbn.getText();
        String editorial = (String) jComboBoxEditorial.getSelectedItem();
        String encuadernacion = "";

        int editorialSeleccionada = jComboBoxEditorial.getSelectedIndex();
        if (editorialSeleccionada == 1 | editorialSeleccionada == 2) {
            encuadernacion = (String) jComboBoxTipoEncu.getSelectedItem();
        }

        String materias = (String) jComboBoxMaterias.getSelectedItem();
        boolean opcion1CheckBox = jCheckBoxOpcion1.isSelected();
        boolean opcion2CheckBox = jCheckBoxOpcion2.isSelected();
        boolean opcion3CheckBox = jCheckBoxOpcion3.isSelected();
        Date fechaPrestamo = (Date) jSpinnerFechaPrestamo.getValue();
        Date fechaEntrega = (Date) jSpinnerFechaEntrega.getValue();

        if (!(nombreApellidos.equals("") || titulo.equals("") || dni.equals("") || autor.equals("") || telefono.equals("") || isbn.equals(""))) {
            System.out.println("Nombre y Apellidos: " + nombreApellidos);
            System.out.println("Título del libro: " + titulo);
            System.out.println("DNI: " + dni);
            System.out.println("Autor del libro: " + autor);
            System.out.println("Teléfono: " + telefono);
            System.out.println("ISBN: " + isbn);
            System.out.println("Editorial: " + editorial);

            if (!(encuadernacion.equals(""))) {
                System.out.println("Tipo de encuadernación: " + encuadernacion);
            }

            System.out.println("Materias: " + materias);

            if (opcion1CheckBox) {
                System.out.println("Seleccionado: " + jCheckBoxOpcion1.getText());
            }

            if (opcion2CheckBox) {
                System.out.println("Seleccionado: " + jCheckBoxOpcion2.getText());
            }

            if (opcion3CheckBox) {
                System.out.println("Seleccionado: " + jCheckBoxOpcion3.getText());
            }

            System.out.println("Fecha préstamo libro: " + fechaPrestamo);
            System.out.println("Fecha entrega libro: " + fechaEntrega);

            JOptionPane.showMessageDialog(this, "Registro guardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            jTextFieldNombre.setText("");
            jTextFieldTitulo.setText("");
            jTextFieldDni.setText("");
            jTextFieldAutor.setText("");
            jTextFieldTelefono.setText("");
            jTextFieldIsbn.setText("");
            jComboBoxEditorial.setSelectedIndex(0);
            jComboBoxTipoEncu.setSelectedIndex(0);
            jComboBoxMaterias.setSelectedIndex(0);
            topics(jComboBoxMaterias.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que rellenar todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void topics(int indice) {

        switch (indice) {
            case 0:
                jCheckBoxOpcion1.setText("Análisis de alimentos");
                jCheckBoxOpcion2.setText("Industria alimentaria");
                jCheckBoxOpcion3.setText("Industria alimentaria");
                break;
            case 1:
                jCheckBoxOpcion1.setText("Neurología");
                jCheckBoxOpcion2.setText("Patología");
                jCheckBoxOpcion3.setText("Medicina general");
                break;
            case 2:
                jCheckBoxOpcion1.setText("Derecho privado");
                jCheckBoxOpcion2.setText("Derecho público");
                jCheckBoxOpcion3.setText("Derecho militar");
                break;
            case 3:
                jCheckBoxOpcion1.setText("Flamenco");
                jCheckBoxOpcion2.setText("Música clásica");
                jCheckBoxOpcion3.setText("Teoría e historia de la música");
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckBoxOpcion1;
    private javax.swing.JCheckBox jCheckBoxOpcion2;
    private javax.swing.JCheckBox jCheckBoxOpcion3;
    private javax.swing.JComboBox<String> jComboBoxEditorial;
    private javax.swing.JComboBox<String> jComboBoxMaterias;
    private javax.swing.JComboBox<String> jComboBoxTipoEncu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerFechaEntrega;
    private javax.swing.JSpinner jSpinnerFechaPrestamo;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldIsbn;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
